package launcher

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"github.com/marenzo/claudex/internal/config"
)

// ClaudeSettings is the Claude Code settings file generated by the installer
// and passed to claude with --settings.
type ClaudeSettings struct {
	Env         map[string]string `json:"env"`
	Model       string            `json:"model"`
	EffortLevel string            `json:"effortLevel"`
	Permissions struct {
		Deny []string `json:"deny"`
	} `json:"permissions"`
}

// Families maps Claude model families to the GPT model that serves them.
var Families = map[string]string{"FABLE": "astra", "OPUS": "sol", "SONNET": "terra", "HAIKU": "luna"}

const suffix = " (Codex subscription)"

// Settings derives Claude Code settings from the gateway configuration.
func Settings(cfg config.Config) (ClaudeSettings, error) {
	model, ok := config.FindModel(cfg.Model)
	if !ok {
		return ClaudeSettings{}, fmt.Errorf("unsupported model %q: choose astra, terra, sol, luna, or a Claude family", cfg.Model)
	}
	small, _ := config.FindModel(Families["HAIKU"])
	env := map[string]string{
		"ANTHROPIC_BASE_URL":                         "http://" + cfg.Listen,
		"ANTHROPIC_API_KEY":                          "",
		"ANTHROPIC_MODEL":                            model.ID,
		"ANTHROPIC_DEFAULT_MODEL":                    model.ID,
		"ANTHROPIC_CUSTOM_MODEL_OPTION":              model.ID,
		"ANTHROPIC_CUSTOM_MODEL_OPTION_NAME":         model.Name + suffix,
		"ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION":  "Local Claudex proxy",
		"ANTHROPIC_SMALL_FAST_MODEL":                 small.ID,
		"CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY": "1",
		"CLAUDE_CODE_MAX_CONTEXT_TOKENS":             strconv.Itoa(cfg.ContextWindow),
		"CLAUDE_CODE_AUTO_COMPACT_WINDOW":            strconv.Itoa(cfg.CompactWindow),
		"API_TIMEOUT_MS":                             "600000",
	}
	for family, alias := range Families {
		target, _ := config.FindModel(alias)
		env["ANTHROPIC_DEFAULT_"+family+"_MODEL"] = target.ID
		env["ANTHROPIC_DEFAULT_"+family+"_MODEL_NAME"] = target.Name + suffix
	}
	settings := ClaudeSettings{Env: env, Model: model.ID, EffortLevel: cfg.ReasoningEffort}
	if cfg.ReasoningEffort == "ultra" {
		settings.EffortLevel = "ultracode"
	}
	settings.Permissions.Deny = []string{"Artifact"}
	return settings, nil
}

func encodeJSON(value any) ([]byte, error) {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

// RewriteArgs maps friendly model aliases and the ultra effort to the values
// Claude Code understands. Arguments after "--" are left untouched.
func RewriteArgs(args []string) []string {
	out := append([]string(nil), args...)
	for i := 0; i < len(out); i++ {
		arg := out[i]
		switch {
		case arg == "--":
			return out
		case arg == "--model" && i+1 < len(out):
			out[i+1] = canonicalAlias(out[i+1])
			i++
		case strings.HasPrefix(arg, "--model="):
			out[i] = "--model=" + canonicalAlias(strings.TrimPrefix(arg, "--model="))
		case arg == "--effort" && i+1 < len(out) && out[i+1] == "ultra":
			out[i+1] = "ultracode"
			i++
		case arg == "--effort=ultra":
			out[i] = "--effort=ultracode"
		}
	}
	return out
}

// canonicalAlias expands direct aliases only (astra, terra, sol, luna). Claude
// family names such as "opus" are passed through so Claude Code resolves them.
func canonicalAlias(value string) string {
	for _, model := range config.Models() {
		if model.Alias == strings.ToLower(value) {
			return model.ID
		}
	}
	return value
}
